// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpRQVB5l7llS4oROPP0X_4CMuIHXHnKo',
    appId: '1:837753736142:web:58b0bdb7daeac46e3e799f',
    messagingSenderId: '837753736142',
    projectId: 'coconutagencement-96dcd',
    authDomain: 'coconutagencement-96dcd.firebaseapp.com',
    storageBucket: 'coconutagencement-96dcd.firebasestorage.app',
    measurementId: 'G-CCKG66VVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMpIlNBi8rgzm9xs8X6xAFywfMnbHgoM',
    appId: '1:837753736142:android:451ec1c076f3cc7b3e799f',
    messagingSenderId: '837753736142',
    projectId: 'coconutagencement-96dcd',
    storageBucket: 'coconutagencement-96dcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYoFpf2wfyUCrJrHBxZxjfQ2yK5fAhxL0',
    appId: '1:837753736142:ios:d901893ceba6c49f3e799f',
    messagingSenderId: '837753736142',
    projectId: 'coconutagencement-96dcd',
    storageBucket: 'coconutagencement-96dcd.firebasestorage.app',
    iosBundleId: 'com.example.coconutAgencement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYoFpf2wfyUCrJrHBxZxjfQ2yK5fAhxL0',
    appId: '1:837753736142:ios:d901893ceba6c49f3e799f',
    messagingSenderId: '837753736142',
    projectId: 'coconutagencement-96dcd',
    storageBucket: 'coconutagencement-96dcd.firebasestorage.app',
    iosBundleId: 'com.example.coconutAgencement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdpRQVB5l7llS4oROPP0X_4CMuIHXHnKo',
    appId: '1:837753736142:web:c0729cd4279678a73e799f',
    messagingSenderId: '837753736142',
    projectId: 'coconutagencement-96dcd',
    authDomain: 'coconutagencement-96dcd.firebaseapp.com',
    storageBucket: 'coconutagencement-96dcd.firebasestorage.app',
    measurementId: 'G-FPRDP80WF6',
  );
}
